<Project Sdk="Godot.NET.Sdk/4.3.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net7.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'ios' ">net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>PropertyTycoon</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="C:\Users\alals\.nuget\packages\gdunit4.api\4.3.1\contentFiles\any\net8.0\LICENSE" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Objects\" />
    <Folder Include="Scenes\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="gdUnit4.api" Version="4.3.1" />
    <PackageReference Include="gdUnit4.test.adapter" Version="2.0.0" />
  </ItemGroup>
</Project>